version: '3.7'

services:
   db:
     image: mysql:5.7
     volumes:
       - /home/sonnyyu/docker/db_data:/var/lib/mysql
       - /home/sonnyyu/docker/db_log:/var/log/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
       - "3306:3306"
     command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log --log_error=/var/log/mysql/error.log

